# ----
# Site

title: Biométricos y Software para Control de Asistencia
author: Dolsite Tech
url: https://dolsite.com
baseurl:
google_analytics_key: G-YLGVJ6D4D4

# Values for the jekyll-seo-tag gem (https://github.com/jekyll/jekyll-seo-tag)
logo: /logo.png
description: Soluciones biométricas y software para tu empresa.
author:
  name: Dolsite
  email: 2005maldonado@gmail.com
  twitter: # twitter username without the @ symbol
social:
  name: Dolsite Tech
  links:
    - https://www.facebook.com/profile.php?id=61581708354224

# -----
# Build

timezone: Etc/UTC

collections:
  staff_members:
    _icon: account_circle
    _hide_content: true
    _options:
      image:
        width: 250
        height: 250

permalink: pretty

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      _options:
        content:
          width: 1880
          height: 1880
          uploads_dir: "/images/posts/"
  -
    scope:
      path: ""
    values:
      layout: "default"

donation_embed: '<script src="https://donorbox.org/widget.js" type="text/javascript"></script><iframe src="https://donorbox.org/embed/give-sheep-the-vote?hide_donation_meter=true" height="685px" width="100%" style="max-width:425px; min-width:310px" seamless="seamless" id="dbox-form-embed" name="donorbox" frameborder="0" scrolling="no"></iframe>'
newsletter_action: "https://dolsite.us6.list-manage.com/subscribe/post?u=6db4ac2c575d1906e264a030b&id=a47d2caa18&f_id=0032b0e0f0"

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag

exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - LICENCE

# -----------
# CloudCannon

_options:
  header_background_image:
    width: 1880
    height: 1880
  newsletter_background_image:
    width: 1880
    height: 1880
